
GAME_HEIGHT = 720
GAME_WIDTH = 1280
FPS_LIMIT = 0

ENEMIES_TO_SPAWN = 200


FORWARD_KEYS = [pygame.K.w]
BACKWARDS_KEYS = [pygame.K_s]
LEFT_KEYS = [pygame.K_a]
RIGHT_KEYS = [pygame.K_d]

RENDER_HITBOXES = True